version: '2'
services:
  comp353_httpd:
    build:
      context: .
    container_name: "comp353_httpd"
    ports:
      - "8080:80"
    volumes:
      - "./server/:/var/www/html/"

  comp353_mysql:
    image: mysql:5.6
    container_name: "comp353_mysql"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: "whatever"
      MYSQL_USER: "lvc353_2"
      MYSQL_PASSWORD: "Pl2n05Q1"
      MYSQL_DATABASE: "lvc353_2"
