version: '2'
services:
  comp353_httpd:
    build:
      context: .
    container_name: "comp353_httpd"
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html/"

  comp353_mysql:
    image: mysql:5.6
    container_name: "comp353_mysql"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/"
    env_file: "./sikrits.env"
